<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class DesignationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $designations = [
            'ADMIN STAFF', 'ACCOUNTING ADMIN STAFF', 'ACCOUNTING STAFF', 'ACCOUNTING SUPERVISOR',
            'ACCOUNTING SUPERVISOR - AP', 'ACCOUNTING SUPERVISOR - AR', 'ACCOUNTING SUPERVISOR - SALES',
            'ADMIN SUPERVISOR', 'ADMIN STAFF I', 'ADMIN STAFF II', 'ADMIN STAFF III',
            'AREA MANAGER', 'AREA SUPERVISOR', 'ASST. TEAM LEADER', 'ASSISTANT BAKER',
            'ASSISTANT TL', 'AUDIT STAFF', 'BAKER', 'BAKER ASSISTANT', 'B & D FRANCHISE MANAGER',
            'BOH STAFF', 'BOX ASSEMBLE', 'BUSINESS PROCESS ADMIN', 'BUSINESS PROCESS MANAGER',
            'CAKE CHECKER', 'CAKE DECORATOR', 'CAKE DECORATOR - ASSISTANT', 'CAKE DEPANNING',
            'CAKE PACKAGING', 'CAKE SANITATION', 'CAKE SEGREGATOR', 'CAKE SEGRAGATOR',
            'CASHIER', 'CHECKER', 'CLUSTER BAKER', 'COMPANY DRIVER', 'CONSTRUCTION ADMIN',
            'CONSTRUCTION STAFF', 'CONSTRUCTION SUPERVISOR', 'CORPORATE PLANNING OFFICER',
            'CRATES WASHER', 'DELIVERY HELPER', 'DISPATCHER', 'DOUGH MASTER', 'DRIVER',
            'ELECTRICIAN', 'ENCODER', 'FIELD TRAINER', 'FINACE MANAGER', 'FOH STAFF',
            'FOH STAFF - ORDER TAKER/ASSEMBLER', 'FRANCHISE RECRUITMENT SPECIALIST',
            'HEAD - PREMIX', 'HELPER', 'HELPER - DELIVERY', 'HR ADMIN STAFF',
            'HR COORDINATOR', 'HR MANAGER', 'HR RECRUITMENT SPECIALIST', 'HR SPECIALIST-EMPLOYEE RELATIONS',
            'HR STAFF - COMPENSATION & BENEFITS', 'HR SUPERVISOR', 'I.C.T SUPERVISOR',
            'I.T ADMIN STAFF', 'IT STAFF', 'LABORER', 'LEARNING AND DEVELOPMENT ADMIN ASSISTANT',
            'LEASING ADMIN STAFF', 'LIASON', 'LIASON OFFICER', 'LOGISTICS ADMIN STAFF',
            'LOGISTICS SUPERVISOR', 'LOAF ASSISTANT', 'LOAF BAKER', 'LOAF BAKER ASST.',
            'LOAF PACKAGING', 'LOAF SEGREGATOR', 'MAINTENANCE', 'MAINTENANCE PERSONNEL',
            'MAINTENANCE STAFF', 'MARKETING STAFF', 'MECHANIC', 'NIGHT SHIFT ENCODER',
            'OPERATIONS AREA SUPERVISOR', 'OPERATIONS MANAGER', 'OPERATION ADMIN',
            'OVEN MAN', 'OVENMAN', 'PACKAGING STAFF', 'PACKAGING STAFF - CAKE',
            'PAIL WASHER', 'PAYROLL OFFICER', 'PEOPLE DEVELOPMENT OFFICER',
            'PERFORMANCE EVALUATION OFFICER', 'PLANT MANAGER', 'PREMIX ADMIN STAFF',
            'PREMIX CHECKER ASST.', 'PREMIX STAFF', 'PREMIX - STAFF', 'PROCUREMENT ASSISTANT',
            'PRODUCTION ASSISTANT SUPERVISOR', 'PRODUCTION STAFF', 'PROJECT COORDINATOR',
            'PURCHASER', 'PURCHASING STAFF', 'QUALITY ASSURANCE',
            'QUALITY ASSURANCE OFFICER', 'QUALITY ASSURANCE SUPERVISOR',
            'R & D ASSISTANT', 'R & D SPECIALIST', 'RECRUITMENT ASSOCIATE',
            'REPROCESSOR', 'RESEARCH AND DEVELOPMENT SUPERVISOR', 'SANITATION',
            'SEGREGATOR - LOAF', 'SEGREGATOR CAKE', 'SHIFT MANAGER',
            'SITE DEVELOPMENT SPECIALIST', 'SKILLED MECHANIC', 'STOCKMAN',
            'STORE MANAGER', 'STORE OPENING INCHARGE', 'STORE SUPERVISOR',
            'SUPPLY CHAIN SUPERVISOR', 'SWEET BAKER', 'SWEET CHECKER',
            'SWEET SEGREGATOR', 'TAM LEADER', 'TAXATION AND COMPLIANCE ADMIN STAFF',
            'TAXATION CLERK', 'TAXATION STAFF', 'TAXATION SUPERVISOR',
            'TEAM LEADER', 'TEAM LEADER - BASE CAKE', 'TEAM LEADER - CAKE PACKAGING',
            'TEAM LEADER - LOAF PACKING', 'TEAM LEADER - OVEN',
            'TEAM LEADER - SWEETS PACKING', 'TEAM LEADER LOAF',
            'TEAM LEADER LOAF & SWEETS PACKAGING', 'TEAM LEADER SWEETS',
            'TEAM LEADER OVEN', 'TIMEKEEPER', 'TRAINER', 'TRAINER - FOH',
            'TRAINING FIELD OFFICER', 'TRAINING MANAGER', 'TRAINING SPECIALIST',
            'TRAINING SUPERVISOR', 'UTILITY', 'UTILITY/SANITATION - CAKE',
            'WAREHOUSE ITEM IN-CHARGE', 'WAREHOUSE STAFF', 'WAREHOUSE SUPERVISOR',
            'WASHER', 'WELDER', 'WET PREMIX', 'WET PREMIX ASSISTANT',
            'WET PREMIX CONTROLLER'
        ];

        // Insert unique designations into the database
        foreach ($designations as $designation) {
            DB::table('designations')->insertOrIgnore(['name' => $designation]);
        }
    }
}
